### ISSUE TITLE
So I'm told that easy install isn't sufficient for all functions to work, but your detailed install is in French, and isn't detailed at all.

### ISSUE THREAD

**Issue by hostquota** [AlternC/easy-install#12]
Sio how can I get the full functionality of Alternc? I translated all that French into English, yet it doesn't even install php. It's incomplete. Now becuse I ask questions, I get these really impolite respnses from Camlafft.
So if you don't want me to use your panel, just say so instead of deleting my posts.
Stuff your panel you ignorant git.

**Comment by hostquota** [comment]
You should take some lessons in politeness, I for one will never touch this panel again. It's totally unsupported, has features that will not work through easy install (so what is the point of easy install then?) and after 11 years development you still can't put together proper instructions for a normal install, and on top of that you get so rude just because I'm asking questions. I don't think camlafft should be answering questions here if he can't maintain any level of decent interaction with others. I'm very tempted to use a four letter word beginning with F to tell camlafft what to do with himself. Ignorant git.

**Comment by camlafit** [comment]
Hi

Thanks for you return. Sorry if my english has cause some troubles. I don't want offense you. You're welcome.

About language, we have again some problems. Alternc project come from french team and we must translate many part of code. Some part of code and wiki are yet translated and all new commit/work/... try to use in priority english. Is not perfect and team continue his effort.
You can check this work on our [Alternc wiki](https://github.com/AlternC/AlternC/wiki/)

About deleted posts, we don't delete anything, all question/help are welcomes. I've only close some issues and invite you to (re)open on correct project.
* [Easy-install project](https://github.com/AlternC/easy-install/) is related only to help admins sys user to install a default alternc instance and some standard/official plugin.
* [alternc project](https://github.com/AlternC/Alternc/) is main repository and is related to core project. Some issues opened and close should be affected to this project (as how to create plugin, how to manage panel, ...)
* Plugin project can have own repository as [Alternc mailman](https://github.com/AlternC/alternc-mailman) but other can be in [core alternc repository](https://github.com/AlternC/Alternc/). 
This behavior is due to alternc history.

About help, following your great suggestion, some new wiki page were opened : 
* https://github.com/AlternC/AlternC/wiki/Plugin-:-Add-to-menu
* https://github.com/AlternC/AlternC/wiki/Plugin-:-Provide-a-panel-page
It's not perfect but can help how to find sample on main code source. As previously said, better way to understand how to create a plugin looks, actually, to read source code.

To complete this a new repository was opened, to provide a sample plugin creation : 
* https://github.com/AlternC/alternc-borgbackup

In each case, we are agree, is not perfect. With your help, this work is in progress.


Thanks a lot,

**Comment by fser** [comment]
Hi @hostquota,

I think you made your point here. Speaking about politeness, I think this is rude from you to personnaly insult one of the guys who takes time to provide you information. 
Dirty linen shouldn't be washed in public.

That being said: yes, AlternC is a bit of a **** in *** *** to install and to get into.
You want to help? Great!
Indeed easy_install does not provide the full package, and not even a working installation on jessie (but it works on wheezy though (pro: there was no systemd at that time ;)). You may want to make a pull request to make it work properly on jessie, and that would actually make things move forward.

If you want to talk about the project management, and what things should be done (because yes, your opinion matters, especially because you have a newer look on it), please join the mailing list and help us start something. Also, feel free to join IRC if you want to talk synchronously with people.

**Comment by innoticFR** [comment]
(@fser To be honest, it's quite funny to read "ignorant git" on Github. At first sight, I thought it was a SVN nostalgic.)

@hostquota Installing AlternC is difficult for everyone and we are working on it. Sorry for that. At the same time, and to be really honest, it will always require some patience to install a perfect and custom hosting environment. Your experience and difficulties can benefit to the project. If you can help with the translations of the installation in English, we'd love to.

Personnaly, I had a major headache installing AlternC on a Debian Jessie a few months ago on a 1000 users installation. But I decided to help improving the project, and my installation is now fully working. I tried also to translate the best that I can the web interface in both Spanish and English, but I have to admit that I am not native English speaker.

**Comment by albancrommer** [comment]
I'm not understanding why you're seeing french, as the whole bash output should appear in english.
Please provide a more reproducible bug and a focused scope :)
